backend:
  name: github
  repo: pwenxiang51-wq/my-blog
  branch: main
  base_url: https://blog.222382.xyz
  auth_endpoint: api/oauth

media_folder: "source/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "文章"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "日期", name: "date", widget: "datetime"}
      - {label: "标签", name: "tags", widget: "list"}
      - {label: "分类", name: "categories", widget: "list", required: false}
      - {label: "正文", name: "body", widget: "markdown"}
      skip_render:
  - admin/**
