backend:
  name: github
  repo: pwenxiang51-wq/my-blog
  branch: master
  # 指向你刚刚创建的 Cloudflare Worker 门卫
  base_url: https://blog-auth.wenxiang0100.workers.dev
  auth_endpoint: auth

media_folder: "source/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "我的文章"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "正文内容", name: "body", widget: "markdown"}
